### ISSUE TITLE
500 : Internal Server Error when login Jupyterhub

### ISSUE THREAD

**Issue by yh0903** [MD2Korg/CerebralCortex#3]
Hey!

I followed the instructions, and when I was trying to use Jupyter Notebook after I enter the default account and password, I met an error:
500: Internal Server Error Failed to start your server on the last attempt. Please contact admin if the issue persists.
Are there any methods that can fix this problem? 

Thanks

**Comment by twhnat** [comment]
@yh0903 We just noticed this today and found the solution.  Right now, the master branch is undergoing a lot of changes and we will tag a release once it stabalizes.  To address this problem, just change this line https://github.com/MD2Korg/CerebralCortex/blob/master/docker-compose.yml#L72

from version 2.4.0 to latest.  The 2.4.0 docker container contains a mis-configured jupyter environment and the latest properly builds it.

**Comment by nasirali1** [comment]
@yh0903 we have fixed the issue. Please checkout the master branch. Let us know if you face any other issue.

**Comment by nasirali1** [comment]
@yh0903 we have fixed the issue. Please checkout the master branch. Let us know if you face any other issue.
